colors:
  primary:
    background: '0x__[terminal_background]__'
    foreground: '0x__[terminal_foreground]__'
  cursor:
    text: '0x__[terminal_text]__'
    cursor: '0x__[terminal_cursor]__'
  normal:
    black: '0x__[terminal_normal_black]__'
    red: '0x__[terminal_normal_red]__'
    green: '0x__[terminal_normal_green]__'
    yellow: '0x__[terminal_normal_yellow]__'
    blue: '0x__[terminal_normal_blue]__'
    magenta: '0x__[terminal_normal_magenta]__'
    cyan: '0x__[terminal_normal_cyan]__'
    white: '0x__[terminal_normal_white]__'
  bright:
    black: '0x__[terminal_bright_black]__'
    red: '0x__[terminal_bright_red]__'
    green: '0x__[terminal_bright_green]__'
    yellow: '0x__[terminal_bright_yellow]__'
    blue: '0x__[terminal_bright_blue]__'
    magenta: '0x__[terminal_bright_magenta]__'
    cyan: '0x__[terminal_bright_cyan]__'
    white: '0x__[terminal_bright_white]__'
  indexed_colors:
    - {index: 16, color: '0x__[terminal_indexed_16]__'}
    - {index: 17, color: '0x__[terminal_indexed_17]__'}
    - {index: 18, color: '0x__[terminal_indexed_18]__'}
    - {index: 19, color: '0x__[terminal_indexed_19]__'}
    - {index: 20, color: '0x__[terminal_indexed_20]__'}
    - {index: 21, color: '0x__[terminal_indexed_21]__'}
background_opacity: __[colors_float_alpha]__
env:
  TERM: __[term]__
window:
  padding:
    x: 10
    y: 10
  dynamic_padding: false
  dynamic_title: true
font:
  normal:
    family: __[fonts_mono]__
  size: __[fonts_size_terminal]__
cursor:
  unfocused_hollow: true
live_config_reload: true
