#!/usr/bin/env sh
yad \
--mouse \
--posy=32 \
--sticky \
--fixed \
--on-top \
--undecorated \
--splash \
--close-on-unfocus \
--skip-taskbar \
--selectable-labels \
--no-buttons \
--form \
--field='􀆨 Poweroff':FBTN \
--field='􀅉 Reboot':FBTN \
--field='􀆽 Suspend':FBTN \
--field='􀎡 Lock':FBTN 'systemctl poweroff' 'systemctl reboot' 'systemctl suspend' 'lockscreen'
