#!/usr/bin/env sh
connections=$($DOTFILES/scripts/polybar/print_network.py)

yad \
--mouse \
--posy=32 \
--sticky \
--fixed \
--on-top \
--undecorated \
--splash \
--close-on-unfocus \
--skip-taskbar \
--selectable-labels \
--no-buttons \
--text="$connections" \
