#!/usr/bin/env python

from requests import get, adapters, exceptions
from sys import exit, argv
from pathlib import Path
from random import choice
from yaml import safe_load as yaml_load
from argparse import ArgumentParser
from plumbum import FG, colors
from plumbum.cmd import xdg_user_dir, xwallpaper


def download_file(path, url):
    filename = url.split('/')[-1]
    downloaded_path = path.joinpath(path, filename)
    print(colors.info | 'Saving to:', downloaded_path)

    download_stream = get(url, stream=True)
    with open(downloaded_path, 'wb') as img:
        img.write(download_stream.content)

    return downloaded_path


def wallheaven_download_random(path):
    API_URL = 'https://wallhaven.cc/api/v1/search?'
    PARAMS = {
        'q': '+nature+landscape',
        'categories': '100',
        'purity': '100',
        'atleast': '2560x1440',
        'sorting': 'random'
    }

    try:
        r = get(API_URL, params=PARAMS)
        r.raise_for_status()
    except exceptions.ConnectionError or exceptions.HTTPError:
        return pick_random_existing(path)

    data = yaml_load(r.text)
    url = data['data'][0]['path']
    print(colors.info | 'Got image url:', url)

    return download_file(path, url)


def set_wallpaper(path):
    if path.is_file() and path.suffix in ['.jpg', '.png']:
        xwallpaper["--zoom", path] & FG
    else:
        print(colors.fatal | 'Wrong file format or it does not exist!')
        exit(1)


def pick_random_existing(path):
    print(colors.warn | 'Could not connect to wallheaven.cc!')
    print(colors.info | 'Trying to load random downloaded image: ', end='')

    wallpaper = choice(list(path.glob('*.[jp][pn][g]')))
    if wallpaper:
        print(wallpaper)
        return wallpaper
    else:
        print(path, colors.fatal | 'is empty!')
        exit(1)


parser = ArgumentParser(description='Simple xwallpaper wrapper. \
    Downloads a random image from wallheaven.cc and sets it as a \
    desktop background if none arguments provided.')
parser.add_argument('path', metavar='PATH', type=Path, nargs='?',
                    help='A path to existing wallpaper.')
args = parser.parse_args()

default_path = Path(xdg_user_dir('PICTURES').rstrip()).joinpath('wallpapers')

if len(argv) > 1:
    set_wallpaper(args.path)
else:
    file = wallheaven_download_random(default_path)
    set_wallpaper(file)
