#!/usr/bin/env fish

if not test -e $DOTFILES/dark_mode/isdark;
    exit 1
end
read -g ISDARK < $DOTFILES/dark_mode/isdark

function wallheaven
  set link (curl -G -s \
    (string join '' "https://wallhaven.cc/api/v1/search?" \
      "q=+nature+landscape&" \
      "categories=100&" \
      "purity=100&" \
      "resolutions=1920x1080&" \
      "sorting=random") \
    | jq -r '.data[0].path')

  set file (basename $link)
  curl -s $link -o /tmp/$file
  set -g wp /tmp/$file

  echo Found: $link
end

if [ -z $argv ]
  echo "Wallpaper not provided, picking a random one..."
  wallheaven
else if [ -e $argv ]; and string match -r '.jpg|.png' -- $argv &> /dev/null
  set wp $argv
else
  echo 'Not a .jpg or .png file!'
  exit 1
end


set size (xdpyinfo | awk '/dimensions:/ { print $2; exit }')
if [ (identify -format '%w' $wp) -le '512' ]
	xwallpaper --tile $wp
else
  mogrify -resize $size $wp
	xwallpaper --zoom $wp
end

echo Path: $wp

jq --arg wp $wp '.wallpaper |= $wp' $DOTFILES/config.json | \
xsel -s && xsel -s -o > $DOTFILES/config.json
