#!/usr/bin/env fish

if [ (jq -r '.mode' $DOTFILES/config.json) = $argv[1] ]
  echo "Already set"
  exit 1
else
  set mode $argv[1]
  jq --arg mode $mode '.mode |= $mode' $DOTFILES/config.json | \
  xsel -s && xsel -s -o > $DOTFILES/config.json
end

set base (jq -r ".colors.$mode.base" $DOTFILES/config.json)
set alt (jq -r ".colors.$mode.alt" $DOTFILES/config.json)
set text (jq -r ".colors.$mode.text" $DOTFILES/config.json)
set text_alt (jq -r ".colors.$mode.text_alt" $DOTFILES/config.json)
set tr_hex (jq -r ".colors.transparency.hex" $DOTFILES/config.json)
set tr_dec (jq -r ".colors.transparency.dec" $DOTFILES/config.json)
set tr_float (jq -r ".colors.transparency.float" $DOTFILES/config.json)

set gtk_theme (jq -r ".theme.gtk.$mode" $DOTFILES/config.json)
set kvtheme (jq -r ".theme.kvantum.$mode" $DOTFILES/config.json)
set icon_theme (jq -r ".icons.$mode" $DOTFILES/config.json)

echo Changed mode: $mode

# Alacritty
echo Setting Alacritty...
yq -r \
  --arg base (echo "0x"$base) \
  --arg text (echo "0x"$text) \
  --arg text_alt (echo "0x"$text_alt) \
  '.colors.primary.background |= $base | .colors.primary.foreground |= $text | .colors.cursor.text |= $text | .colors.cursor.cursor |= $text_alt' \
  $DOTFILES/config/alacritty/alacritty.yml -Y | \
  xsel -s && xsel -s -o > $DOTFILES/config/alacritty/alacritty.yml
  awk -v tr=$tr_float '{if ($1 == "background_opacity:") {$2 = tr} print}' $DOTFILES/config/alacritty/alacritty.yml | \
  xsel -s && xsel -s -o > $DOTFILES/config/alacritty/alacritty.yml

# Polybar
echo Setting Polybar...
set script '
{
  sub("background = #.+", "background = #" tr_hex base)
  sub("foreground = #.+", "foreground = #" tr_hex text)
  print
}
'
gawk \
  -v base=$base \
  -v text=$text \
  -v tr_hex=$tr_hex \
  $script $DOTFILES/config/polybar/config | \
  xsel -s && xsel -s -o > $DOTFILES/config/polybar/config

# Dunst
echo Setting Dunst...
set script '
{
  tr = 100 - tr_float * 100
  sub("background = .+", "background = \"#"base"\"")
  sub("foreground = .+", "foreground = \"#"text"\"")
  sub("frame_color = .+", "frame_color = \"#"alt"\"")
  sub("transparency = .+", "transparency = "tr)
  print
}
'
gawk \
  -v base=$base \
  -v alt=$alt \
  -v text=$text \
  -v tr_float=$tr_float \
  $script $DOTFILES/config/dunst/dunstrc | \
  xsel -s && xsel -s -o > $DOTFILES/config/dunst/dunstrc

# i3
echo Setting i3...
set script '
{
  if($1 == "client.focused" || $1 == "client.focused_inactive") {
    $2 = "#"alt tr_hex; $3 = "#"alt tr_hex; $5 = "#"base tr_hex;; $6 = "#"base tr_hex;
    $4 = "#"text tr_hex;
  } else if ($1 == "client.unfocused" || $1 == "client.placeholder" || $1 == "client.urgent") {
    $2 = "#"base tr_hex; $3 = "#"base tr_hex; $5 = "#"alt tr_hex;; $6 = "#"alt tr_hex;
    $4 = "#"text tr_hex;
  }
  print
}
'
gawk \
  -v base=$base \
  -v alt=$alt \
  -v text=$text \
  -v tr_hex=$tr_hex \
  $script $DOTFILES/config/i3/config | \
  xsel -s && xsel -s -o > $DOTFILES/config/i3/config

# Rofi
echo Setting Rofi...
set script '
{
  sub("base: .+;","base: #"base tr_hex";")
  sub("alt: .+;","alt: #"alt";")
  sub("text: .+;","text: #"text";")
  sub("text-selected: .+;","text-selected: #"text";")
  print
}
'
gawk \
  -v base=$base \
  -v alt=$alt \
  -v text=$text \
  -v tr_hex=$tr_hex \
  $script $DOTFILES/config/rofi/config.rasi | \
  xsel -s && xsel -s -o > $DOTFILES/config/rofi/config.rasi

# GTK
echo Setting GTK...
set script '
{
  sub("gtk-theme-name=.+","gtk-theme-name="gtk_theme)
  sub("gtk-icon-theme-name=.+","gtk-icon-theme-name="icon_theme)
  print
}
'
gawk \
  -v icon_theme=$icon_theme \
  -v gtk_theme=$gtk_theme \
  $script $DOTFILES/config/gtk-3.0/settings.ini | \
  xsel -s && xsel -s -o > $DOTFILES/config/gtk-3.0/settings.ini

gsettings set org.gnome.desktop.interface gtk-theme $gtk_theme
gsettings set org.gnome.desktop.interface icon-theme $icon_theme

# QT
echo Setting qt5ct and kvantum...
set script '
{
  sub("icon_theme=.+","icon_theme="icon_theme)
  print
}
'
gawk \
  -v icon_theme=$icon_theme \
  $script $DOTFILES/config/qt5ct/qt5ct.conf | \
  xsel -s && xsel -s -o > $DOTFILES/config/qt5ct/qt5ct.conf

sh -c "kvantummanager --set $kvtheme"

### Reload configs ###
echo Reloading...
pkill dunst
nohup $DOTFILES/scripts/dunst-autoicons &> /dev/null &
i3 restart &> /dev/null &
pkill polybar
nohup polybar -r top &> /dev/null &
nohup picom --experimental-backends &> /dev/null &
