#!/usr/bin/env sh
source /etc/os-release

if [[ $NAME == "Arch Linux" ]]; then
	yay -S \
		acpilight \
		alacritty \
		dex \
		dunst \
		fish \
		gnu-free-fonts \
		i3-gaps \
		i3lock-color-git \
		imagemagick \
		pavucontrol \
		picom-git \
		polybar \
		rofi-git \
		stow \
		sxhkd \
		ttf-joypixels \
		wmctrl \
		xclip \
		xdg-user-dirs \
		xdotool \
		xorg-xkill \
		xsel \
		xss-lock \
		yad \
		pamixer \
		jq \
		yq \
		xwallpaper \
		python-xlib \
		materia-gtk-theme \
		kvantum-theme-materia \
		papirus-icon-theme \
;fi
