#!/usr/bin/env sh
source /etc/os-release

if [[ $NAME == "Arch Linux" ]]; then
	yay -S \
		acpi \
		acpilight \
		alacritty \
		blueman \
		dex \
		dunst \
		fish \
		gnome-settings-daemon \
		gnome-themes-extra \
		gnu-free-fonts \
		i3-gaps \
		i3lock-color \
		imagemagick \
		libxpm \
		mate-polkit \
		nm-connection-editor \
		pavucontrol \
		picom-ibhagwan-git \
		polybar \
		qt5-styleplugins \
		qt5ct \
		rofi-git \
		stow \
		sxhkd \
		ttf-joypixels \
		wmctrl \
		xclip \
		xdg-user-dirs \
		xdotool \
		xorg-xkill \
		xsel \
		xss-lock \
		yad \
		pamixer \
		python-pybluez \
;fi
