#!/usr/bin/env fish

set wp (jq -r '.wallpaper' $DOTFILES/config.json)
set size (identify -format "%[fx:w]\n%[fx:h]" $wp)

set brightness (convert $wp \
	-crop 12%x5%+0+0 \
	-scale 1x1 \
	-colorspace Gray \
	-format '%[fx:b]' info:-)

if [ $brightness -ge 0.59 ]
  set ringhl_color (jq -r '.colors.light.base' $DOTFILES/config.json | tr -d "#")
  set ring_color (jq -r '.colors.light.alt' $DOTFILES/config.json | tr -d "#")
  set text_color (jq -r '.colors.light.alt' $DOTFILES/config.json | tr -d "#")
else
  set ringhl_color (jq -r '.colors.dark.base' $DOTFILES/config.json | tr -d "#")
  set ring_color (jq -r '.colors.dark.alt' $DOTFILES/config.json | tr -d "#")
  set text_color (jq -r '.colors.dark.alt' $DOTFILES/config.json | tr -d "#")
end

# import -window root -compress none -thumbnail 640x320 /tmp/scr.png
# ffmpeg -i /tmp/scr.png \
  # -vf boxblur=3:3,eq=brightness=-0.05 \
  # -s 1920x1080 \
  # -y /tmp/wall.png \
  # -hide_banner -loglevel warning

echo $brightness
i3lock -i $wp \
--indicator --force-clock --redraw-thread --time-align 1 \
--bshlcolor=$ringhl_color \
--insidecolor=00000000 \
--insidevercolor=00000000 \
--insidewrongcolor=00000000 \
--keyhlcolor=$ringhl_color \
--linecolor=00000000 \
--ringcolor=$ring_color \
--ringvercolor=$ringhl_color \
--ringwrongcolor=$ringhl_color \
--separatorcolor=00000000 \
--verifcolor=$ringhl_color \
--wrongcolor=$ringhl_color \
\
--timecolor=00000000 \
--datecolor=00000000 \
\
--indpos="15 + r:h - 15 - r" \
--radius=32 \
--ring-width=8 \
\
--timestr="%H:%M" \
--timepos="ix + 10 + r:iy + r / 2" \
--time-font="SF-Pro-Rounded-Heavy" \
--timesize=32 \
\
--wrongtext="" \
--veriftext="" \
--noinputtext="" \
--locktext="" \
--lockfailedtext="" \
